[project]
name = "licensing-specialist"
version = "0.1.2"
description = "App for tracking trainees through the LLQP process."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyside6>=6.10.0",
]
[project.scripts]
l_spec = "licensing.specialist.main:main"
